export * from "./Categories/categories.routes.js"
export * from "./subCategory/subCategory.routes.js"
export *from "./Brands/Brand.routes.js"
export * from "./product/product.routes.js"
export * from "./USER/user.routes.js"